[build]
  command = "npm install -g pnpm && pnpm install && cd packages/db && npx prisma generate && cd ../.. && pnpm run build:packages && cd apps/web && pnpm run build && pnpm run export"
  publish = "apps/web/out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"