[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm run build:packages',
  'cd apps/web && pnpm run build'
]

[start]
cmd = 'cd apps/web && pnpm start'